services:
  postgres:
    container_name: db

    image: postgres:latest

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    ports:
      - "5432:5432"

    restart: always

  orch:
    container_name: orchestrator

    build: ./orch

    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_MAX_ATMPS=5
      - DB_DELAY_ATMPS_S=5

    ports:
     - "8080:8080"

    depends_on:
     - postgres

    restart: always

  agent:
    container_name: agent

    build: ./agent

    ports:
     - "80:3030"

    environment:
      - COMPUTING_POWER=3
      - AGENT_PERIODICITY_MS=250
      - PORT=8080

    depends_on:
     - orch
