services:
  orch:
    build: ./orch
    ports:
     - "8080:8080"
    environment:
      - PORT=8080
  agent:
    build: ./agent
    ports:
     - "80:3030"
    environment:
      - COMPUTING_POWER=5
      - AGENT_PERIODICITY_MS=50
      - PORT=8080
    depends_on:
      - orch
