services:
  postgres:
    container_name: db

    image: postgres:latest

    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mAz0H1zm}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}

    ports:
      - "5432:5432"

  orch:
    container_name: orchestrator

    build: ./orch

    environment:
      - PORT=${PORT:-8080}

      - DB_HOST=db
      - DB_PORT=5432
      - DB_MAX_ATMPS=${DB_MAX_ATMPS:-5}
      - DB_DELAY_ATMPS_S=${DB_DELAY_ATMPS_S:-3}

      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_NAME=${POSTGRES_DB:-postgres}

      - JWT_KEY=${JWT_KEY:-SECRET}
      - HASH_SALT=${HASH_SALT:-SALT}

    ports:
     - "${PORT:-8080}:${PORT:-8080}"

    depends_on:
     - postgres

  agent:
    container_name: agent

    build: ./agent

    ports:
     - "80:3030"

    environment:
      - COMPUTING_POWER=${COMPUTING_POWER:-5}
      - AGENT_PERIODICITY_MS=${AGENT_PERIODICITY_MS:-100}
      - PORT=${PORT:-8080}

    depends_on:
     - orch
